layout_spectrum: 0.2473118
color:
  saturation: 0.2593067
  lightness: 0.8899671
  brandStrength: 0.4329582
  rhythmicContrast: 0.2944632
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.4686711
name: Tejvalluru
